// customerId values match organization IDs in the CRM fixtures.
export const contracts = [
  {
    id: "ctr-1001",
    customerId: "org-100",
    title: "Northstar support agreement",
    status: "active",
    startsOn: "2026-01-01",
    endsOn: "2026-12-31",
    value: 24000,
    currency: "EUR",
    summary: "Business-hours support for observatory operations.",
    clauses: [
      {
        id: "cl-1",
        heading: "Support",
        text: "Support is available Monday to Friday, 09:00–17:00 UTC.",
      },
      {
        id: "cl-2",
        heading: "Renewal",
        text: "Renews only with written agreement from both parties.",
      },
    ],
  },
  {
    id: "ctr-1002",
    customerId: "org-200",
    title: "Juniper implementation project",
    status: "draft",
    startsOn: "2026-10-01",
    endsOn: "2027-03-31",
    value: 48000,
    currency: "EUR",
    summary: "Six-month software implementation across three workshops.",
    clauses: [
      {
        id: "cl-1",
        heading: "Milestones",
        text: "Discovery, prototype, and handover are separate milestones.",
      },
    ],
  },
  {
    id: "ctr-1003",
    customerId: "org-100",
    title: "Northstar evaluation license",
    status: "expired",
    startsOn: "2025-10-01",
    endsOn: "2025-12-31",
    value: 0,
    currency: "EUR",
    summary: "Completed no-cost evaluation of the analysis toolchain.",
    clauses: [
      {
        id: "cl-1",
        heading: "Evaluation",
        text: "Evaluation use only; no production data permitted.",
      },
    ],
  },
  {
    id: "ctr-1004",
    customerId: "org-400",
    title: "Meridian platform subscription",
    status: "active",
    startsOn: "2026-02-01",
    endsOn: "2027-01-31",
    value: 36000,
    currency: "EUR",
    summary: "Annual platform subscription for the analytics team.",
    clauses: [
      {
        id: "cl-1",
        heading: "Support",
        text: "Second-level support with a four-hour response target.",
      },
      {
        id: "cl-2",
        heading: "Renewal",
        text: "Renews automatically unless cancelled 60 days before expiry.",
      },
    ],
  },
  {
    id: "ctr-1005",
    customerId: "org-500",
    title: "Cobalt logistics services agreement",
    status: "active",
    startsOn: "2026-03-01",
    endsOn: "2027-02-28",
    value: 52000,
    currency: "GBP",
    summary: "Transport planning and depot scheduling services.",
    clauses: [
      {
        id: "cl-1",
        heading: "Service levels",
        text: "Dispatch confirmations are issued within two hours of booking.",
      },
      {
        id: "cl-2",
        heading: "Renewal",
        text: "Annual renewal with a 30-day notice period.",
      },
    ],
  },
  {
    id: "ctr-1006",
    customerId: "org-700",
    title: "Lumen clinical data addendum",
    status: "active",
    startsOn: "2026-01-15",
    endsOn: "2026-12-31",
    value: 18500,
    currency: "EUR",
    summary: "Addendum covering clinical data handling and retention.",
    clauses: [
      {
        id: "cl-1",
        heading: "Data protection",
        text: "Records are retained for seven years and stored within the EU.",
      },
    ],
  },
  {
    id: "ctr-1007",
    customerId: "org-1200",
    title: "Kestrel pilot agreement",
    status: "draft",
    startsOn: "2026-11-01",
    endsOn: "2027-04-30",
    value: 30000,
    currency: "USD",
    summary: "Pilot of the telemetry pipeline on two test benches.",
    clauses: [
      {
        id: "cl-1",
        heading: "Milestones",
        text: "Bench setup, calibration, and reporting are separate milestones.",
      },
    ],
  },
  {
    id: "ctr-1008",
    customerId: "org-600",
    title: "Verdant field trial agreement",
    status: "draft",
    startsOn: "2026-10-15",
    endsOn: "2027-01-31",
    value: 12000,
    currency: "EUR",
    summary: "Sensor field trial across two test plots.",
    clauses: [
      {
        id: "cl-1",
        heading: "Evaluation",
        text: "Equipment remains the property of the supplier during the trial.",
      },
    ],
  },
  {
    id: "ctr-1009",
    customerId: "org-900",
    title: "Atlas robotics integration project",
    status: "active",
    startsOn: "2026-04-01",
    endsOn: "2027-03-31",
    value: 76000,
    currency: "EUR",
    summary: "Integration of the control stack with two assembly cells.",
    clauses: [
      {
        id: "cl-1",
        heading: "Milestones",
        text: "Cell integration and safety validation are separate milestones.",
      },
      {
        id: "cl-2",
        heading: "Acceptance",
        text: "Acceptance requires a 30-day uninterrupted production run.",
      },
    ],
  },
  {
    id: "ctr-1010",
    customerId: "org-1100",
    title: "Tidewater monitoring subscription",
    status: "active",
    startsOn: "2026-05-01",
    endsOn: "2027-04-30",
    value: 41000,
    currency: "GBP",
    summary: "Grid monitoring subscription covering three substations.",
    clauses: [
      {
        id: "cl-1",
        heading: "Service levels",
        text: "Alerts are delivered within five minutes of detection.",
      },
      {
        id: "cl-2",
        heading: "Renewal",
        text: "Renews annually with a price review at each anniversary.",
      },
    ],
  },
  {
    id: "ctr-1011",
    customerId: "org-800",
    title: "Basalt legacy support agreement",
    status: "expired",
    startsOn: "2025-01-01",
    endsOn: "2025-12-31",
    value: 15000,
    currency: "EUR",
    summary: "Historic support agreement for the decommissioned site.",
    clauses: [
      {
        id: "cl-1",
        heading: "Support",
        text: "Support ended with the closure of the processing site.",
      },
    ],
  },
  {
    id: "ctr-1012",
    customerId: "org-400",
    title: "Meridian professional services",
    status: "active",
    startsOn: "2026-06-01",
    endsOn: "2026-11-30",
    value: 22500,
    currency: "EUR",
    summary: "Migration support for the reporting warehouse.",
    clauses: [
      {
        id: "cl-1",
        heading: "Milestones",
        text: "Data migration and reporting cutover are separate milestones.",
      },
    ],
  },
  {
    id: "ctr-1013",
    customerId: "org-1000",
    title: "Sable & Finch advisory retainer",
    status: "draft",
    startsOn: "2026-09-01",
    endsOn: "2027-08-31",
    value: 60000,
    currency: "GBP",
    summary: "Advisory retainer for regulatory review work.",
    clauses: [
      {
        id: "cl-1",
        heading: "Renewal",
        text: "Retainer renews annually unless either party gives notice.",
      },
    ],
  },
  {
    id: "ctr-1014",
    customerId: "org-300",
    title: "Harbor library licence",
    status: "expired",
    startsOn: "2025-04-01",
    endsOn: "2026-03-31",
    value: 4800,
    currency: "EUR",
    summary: "Terminal licence for the public reading rooms.",
    clauses: [
      {
        id: "cl-1",
        heading: "Renewal",
        text: "Renewal is subject to annual budget approval.",
      },
    ],
  },
  {
    id: "ctr-1015",
    customerId: "org-500",
    title: "Cobalt driver training package",
    status: "active",
    startsOn: "2026-07-01",
    endsOn: "2026-12-31",
    value: 9600,
    currency: "GBP",
    summary: "Training package for the long-haul driving team.",
    clauses: [
      {
        id: "cl-1",
        heading: "Support",
        text: "Course materials are refreshed at no cost during the term.",
      },
    ],
  },
  {
    id: "ctr-1016",
    customerId: "org-700",
    title: "Lumen support renewal",
    status: "active",
    startsOn: "2026-08-01",
    endsOn: "2027-07-31",
    value: 27000,
    currency: "EUR",
    summary: "Renewed support for clinical scheduling systems.",
    clauses: [
      {
        id: "cl-1",
        heading: "Support",
        text: "On-call cover is provided outside office hours.",
      },
      {
        id: "cl-2",
        heading: "Renewal",
        text: "Renews only with written agreement from both parties.",
      },
    ],
  },
  {
    id: "ctr-1017",
    customerId: "org-900",
    title: "Atlas spare parts agreement",
    status: "draft",
    startsOn: "2026-12-01",
    endsOn: "2027-11-30",
    value: 33000,
    currency: "EUR",
    summary: "Guaranteed availability for critical spare parts.",
    clauses: [
      {
        id: "cl-1",
        heading: "Service levels",
        text: "Critical parts ship within 48 hours of a confirmed order.",
      },
    ],
  },
  {
    id: "ctr-1018",
    customerId: "org-1200",
    title: "Kestrel evaluation licence",
    status: "expired",
    startsOn: "2025-06-01",
    endsOn: "2025-11-30",
    value: 0,
    currency: "USD",
    summary: "Completed evaluation of the telemetry reporting module.",
    clauses: [
      {
        id: "cl-1",
        heading: "Evaluation",
        text: "Evaluation use only; no production data permitted.",
      },
    ],
  },
  {
    id: "ctr-1019",
    customerId: "org-100",
    title: "Northstar data processing addendum",
    status: "active",
    startsOn: "2026-01-01",
    endsOn: "2026-12-31",
    value: 0,
    currency: "EUR",
    summary: "Addendum covering research data handling and retention.",
    clauses: [
      {
        id: "cl-1",
        heading: "Data protection",
        text: "Observation records are pseudonymised before processing.",
      },
    ],
  },
  {
    id: "ctr-1020",
    customerId: "org-1100",
    title: "Tidewater emergency response retainer",
    status: "active",
    startsOn: "2026-09-01",
    endsOn: "2027-08-31",
    value: 18000,
    currency: "GBP",
    summary: "Standby cover for unplanned substation outages.",
    clauses: [
      {
        id: "cl-1",
        heading: "Service levels",
        text: "An engineer is dispatched within four hours of a report.",
      },
    ],
  },
];
