"""Organization IDs match the customerId values in the contracts API."""

ORGANIZATIONS = [
    {
        "id": "org-100",
        "name": "Northstar Observatory",
        "industry": "Research",
        "status": "customer",
        "website": "https://northstar.example.com",
        "contractIds": ["ctr-1001", "ctr-1003", "ctr-1019"],
    },
    {
        "id": "org-200",
        "name": "Juniper Workshop",
        "industry": "Manufacturing",
        "status": "prospect",
        "website": "https://juniper.example.com",
        "contractIds": ["ctr-1002"],
    },
    {
        "id": "org-300",
        "name": "Harbor Library",
        "industry": "Education",
        "status": "lead",
        "website": "https://harbor.example.com",
        "contractIds": ["ctr-1014"],
    },
    {
        "id": "org-400",
        "name": "Meridian Analytics",
        "industry": "Software",
        "status": "customer",
        "website": "https://meridian.example.com",
        "contractIds": ["ctr-1004", "ctr-1012"],
    },
    {
        "id": "org-500",
        "name": "Cobalt Freight",
        "industry": "Logistics",
        "status": "customer",
        "website": "https://cobalt.example.com",
        "contractIds": ["ctr-1005", "ctr-1015"],
    },
    {
        "id": "org-600",
        "name": "Verdant Farms Co-op",
        "industry": "Agriculture",
        "status": "prospect",
        "website": "https://verdant.example.com",
        "contractIds": ["ctr-1008"],
    },
    {
        "id": "org-700",
        "name": "Lumen Health Network",
        "industry": "Healthcare",
        "status": "customer",
        "website": "https://lumen.example.com",
        "contractIds": ["ctr-1006", "ctr-1016"],
    },
    {
        "id": "org-800",
        "name": "Basalt Mining Group",
        "industry": "Mining",
        "status": "churned",
        "website": "https://basalt.example.com",
        "contractIds": ["ctr-1011"],
    },
    {
        "id": "org-900",
        "name": "Atlas Robotics",
        "industry": "Robotics",
        "status": "prospect",
        "website": "https://atlas.example.com",
        "contractIds": ["ctr-1009", "ctr-1017"],
    },
    {
        "id": "org-1000",
        "name": "Sable & Finch",
        "industry": "Legal",
        "status": "lead",
        "website": "https://sablefinch.example.com",
        "contractIds": ["ctr-1013"],
    },
    {
        "id": "org-1100",
        "name": "Tidewater Energy",
        "industry": "Energy",
        "status": "customer",
        "website": "https://tidewater.example.com",
        "contractIds": ["ctr-1010", "ctr-1020"],
    },
    {
        "id": "org-1200",
        "name": "Kestrel Aerospace",
        "industry": "Aerospace",
        "status": "prospect",
        "website": "https://kestrel.example.com",
        "contractIds": ["ctr-1007", "ctr-1018"],
    },
]
CONTACTS = [
    {
        "id": "person-100",
        "organizationId": "org-100",
        "name": "Alex Renner",
        "role": "Operations",
        "email": "alex@northstar.example.com",
    },
    {
        "id": "person-200",
        "organizationId": "org-200",
        "name": "Sam Okafor",
        "role": "Project lead",
        "email": "sam@juniper.example.com",
    },
    {
        "id": "person-300",
        "organizationId": "org-300",
        "name": "Robin Field",
        "role": "Director",
        "email": "robin@harbor.example.com",
    },
    {
        "id": "person-400",
        "organizationId": "org-400",
        "name": "Dana Whitfield",
        "role": "Head of Data",
        "email": "dana@meridian.example.com",
    },
    {
        "id": "person-500",
        "organizationId": "org-500",
        "name": "Priya Raman",
        "role": "Logistics manager",
        "email": "priya@cobalt.example.com",
    },
    {
        "id": "person-600",
        "organizationId": "org-600",
        "name": "Tomas Berg",
        "role": "Cooperative lead",
        "email": "tomas@verdant.example.com",
    },
    {
        "id": "person-700",
        "organizationId": "org-700",
        "name": "Ingrid Halvorsen",
        "role": "Clinical operations",
        "email": "ingrid@lumen.example.com",
    },
    {
        "id": "person-800",
        "organizationId": "org-800",
        "name": "Marek Nowak",
        "role": "Site manager",
        "email": "marek@basalt.example.com",
    },
    {
        "id": "person-900",
        "organizationId": "org-900",
        "name": "Lena Fischer",
        "role": "Robotics engineer",
        "email": "lena@atlas.example.com",
    },
    {
        "id": "person-1000",
        "organizationId": "org-1000",
        "name": "Arthur Penrose",
        "role": "Partner",
        "email": "arthur@sablefinch.example.com",
    },
    {
        "id": "person-1100",
        "organizationId": "org-1100",
        "name": "Nia Osei",
        "role": "Grid operations",
        "email": "nia@tidewater.example.com",
    },
    {
        "id": "person-1200",
        "organizationId": "org-1200",
        "name": "Yusuf Demir",
        "role": "Programme lead",
        "email": "yusuf@kestrel.example.com",
    },
    {
        "id": "person-1300",
        "organizationId": "org-400",
        "name": "Elena Marsh",
        "role": "Procurement",
        "email": "elena@meridian.example.com",
    },
    {
        "id": "person-1400",
        "organizationId": "org-500",
        "name": "Viktor Aalto",
        "role": "Fleet systems",
        "email": "viktor@cobalt.example.com",
    },
    {
        "id": "person-1500",
        "organizationId": "org-100",
        "name": "Grace Lindqvist",
        "role": "Research director",
        "email": "grace@northstar.example.com",
    },
    {
        "id": "person-1600",
        "organizationId": "org-700",
        "name": "Omar Haddad",
        "role": "Quality assurance",
        "email": "omar@lumen.example.com",
    },
    {
        "id": "person-1700",
        "organizationId": "org-900",
        "name": "Sofia Ricci",
        "role": "Finance",
        "email": "sofia@atlas.example.com",
    },
    {
        "id": "person-1800",
        "organizationId": "org-1100",
        "name": "Hannah Brooks",
        "role": "Operations",
        "email": "hannah@tidewater.example.com",
    },
]
ACTIVITIES = [
    {
        "id": "activity-100",
        "organizationId": "org-100",
        "date": "2026-08-01",
        "type": "meeting",
        "summary": "Quarterly support review; no open issues.",
    },
    {
        "id": "activity-200",
        "organizationId": "org-200",
        "date": "2026-08-15",
        "type": "note",
        "summary": "Draft implementation agreement ready for review.",
    },
    {
        "id": "activity-300",
        "organizationId": "org-300",
        "date": "2026-07-20",
        "type": "email",
        "summary": "Sent licence options for the new reading-room terminals.",
    },
    {
        "id": "activity-400",
        "organizationId": "org-400",
        "date": "2026-08-05",
        "type": "meeting",
        "summary": "Reviewed platform roadmap and Q4 data volumes.",
    },
    {
        "id": "activity-500",
        "organizationId": "org-500",
        "date": "2026-08-11",
        "type": "call",
        "summary": "Discussed service levels for the northern distribution hub.",
    },
    {
        "id": "activity-600",
        "organizationId": "org-600",
        "date": "2026-07-28",
        "type": "email",
        "summary": "Field trial scope confirmed for two test plots.",
    },
    {
        "id": "activity-700",
        "organizationId": "org-700",
        "date": "2026-08-18",
        "type": "meeting",
        "summary": "Clinical data addendum walked through with compliance.",
    },
    {
        "id": "activity-800",
        "organizationId": "org-800",
        "date": "2026-03-02",
        "type": "note",
        "summary": "Account closed after the legacy agreement expired.",
    },
    {
        "id": "activity-900",
        "organizationId": "org-900",
        "date": "2026-08-22",
        "type": "meeting",
        "summary": "Integration milestones re-planned for the autumn release.",
    },
    {
        "id": "activity-1000",
        "organizationId": "org-1000",
        "date": "2026-08-09",
        "type": "email",
        "summary": "Advisory retainer scope sent for internal review.",
    },
    {
        "id": "activity-1100",
        "organizationId": "org-1100",
        "date": "2026-08-14",
        "type": "call",
        "summary": "Monitoring subscription expansion across three sites.",
    },
    {
        "id": "activity-1200",
        "organizationId": "org-1200",
        "date": "2026-07-31",
        "type": "note",
        "summary": "Pilot agreement pending legal sign-off.",
    },
    {
        "id": "activity-1300",
        "organizationId": "org-100",
        "date": "2026-09-02",
        "type": "meeting",
        "summary": "Renewal terms for the support agreement discussed.",
    },
    {
        "id": "activity-1400",
        "organizationId": "org-700",
        "date": "2026-09-05",
        "type": "email",
        "summary": "Support renewal quote issued for the coming year.",
    },
    {
        "id": "activity-1500",
        "organizationId": "org-500",
        "date": "2026-09-08",
        "type": "note",
        "summary": "Driver training package scheduled for October.",
    },
    {
        "id": "activity-1600",
        "organizationId": "org-1100",
        "date": "2026-09-10",
        "type": "meeting",
        "summary": "Emergency response retainer reviewed with grid operations.",
    },
]
